apiVersion: v1
kind: Namespace
metadata:
  name: llama-server
---
apiVersion: v1
kind: Service
metadata:
  name: llama-server
  namespace: llama-server
spec:
  ports:
    - name: api
      port: 8090
      targetPort: 8090
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: llama-server
  namespace: llama-server
  labels:
    kubernetes.io/service-name: llama-server
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.8.208
ports:
  - name: api
    port: 8090
    protocol: TCP
