apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/milanpanic2/homelab-main.git
    path: garage-webui
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
