apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.5.15
    helm:
      parameters:
        - name: persistence.enabled
          value: "true"
        - name: persistence.size
          value: "5Gi"
        - name: sidecar.datasources.enabled
          value: "true"
        - name: sidecar.datasources.label
          value: grafana_datasource
        - name: initChownData.enabled
          value: "false"
        - name: securityContext.runAsUser
          value: "472"
        - name: securityContext.runAsGroup
          value: "472"
        - name: securityContext.fsGroup
          value: "472"
        - name: admin.existingSecret
          value: cluster-secret
        - name: admin.userKey
          value: username
        - name: admin.passwordKey
          value: password
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
