apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloakx
    targetRevision: 7.1.11
    helm:
      values: |
        replicas: 1
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "start"
          - "--hostname=keycloak.homelab.com"
        extraEnv: |
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: admin
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-production-secret
                key: password
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-production-secret
                key: username
        database:
          vendor: postgres
          hostname: prod-postgresql-rw.databases.svc.cluster.local
          port: 5432
          database: keycloak
          username: cluster_user
          existingSecret: app-production-secret
          existingSecretKey: password
        http:
          relativePath: /
        proxy:
          enabled: true
          mode: xforwarded
        ingress:
          enabled: true
          ingressClassName: kong
          annotations:
            cert-manager.io/cluster-issuer: homelab-ca-issuer
          rules:
            - host: keycloak.homelab.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: keycloak-tls
              hosts:
                - keycloak.homelab.com
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 1000m
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
