apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 3.1.0
    helm:
      values: |
        proxy:
          type: LoadBalancer
        ingressController:
          enabled: true
          installCRDs: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
