apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 29.7.0
    helm:
      parameters:
        - name: server.persistentVolume.size
          value: "10Gi"
        - name: alertmanager.enabled
          value: "false"
        - name: server.global.scrape_interval
          value: "15s"
        - name: server.extraFlags[0]
          value: web.enable-lifecycle
        - name: server.extraFlags[1]
          value: web.enable-remote-write-receiver
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
