apiVersion: v1
kind: Service
metadata:
  name: vscode-server
  namespace: vscode-https
spec:
  ports:
    - port: 8079
      targetPort: 8079
---
apiVersion: discovery.k8s.io/v1bu
kind: EndpointSlice
metadata:
  name: vscode-server
  namespace: vscode-https
  labels:
    kubernetes.io/service-name: vscode-server
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.8.208
ports:
  - port: 8079
    protocol: TCP
